### ISSUE TITLE
Suggest to loosen the dependency on funcy

### ISSUE THREAD

**Issue by Agnes-U** [elsehow/tendermint-tax#11]
Hi, your project tendermint-tax(commit id: e5e5a81161132e51b6f1a70845c17bd3a10cd424) requires "funcy==1.17" in its dependency. After analyzing the source code, we found that the following versions of funcy can also be suitable, i.e., funcy 1.11, 1.12, 1.13, 1.14, 1.15, 1.16, since all functions that you directly (1 APIs: funcy.seqs.flatten) or indirectly (propagate to 0 funcy's internal APIs and 0 outsider APIs) used from the package have not been changed in these versions, thus not affecting your usage.

Therefore, we believe that it is quite safe to loose your dependency on funcy from "funcy==1.17" to "funcy>=1.11,<=1.17". This will improve the applicability of tendermint-tax and reduce the possibility of any further dependency conflict with other projects. 

May I pull a request to further loosen the dependency on funcy?

By the way, could you please tell us whether such an automatic tool for dependency analysis may be potentially helpful for maintaining dependencies easier during your development?

**Comment by elsehow** [comment]
@Agnes-U Thanks for your comment! I am happy to see a PR on this.

An automatic dependency tool might be useful.

**Comment by Agnes-U** [comment]
Thanks for your reply! Here's the PR #12 :)
