### ISSUE TITLE
pandas 1.3.2 fails on python 3.10

### ISSUE THREAD

**Issue by lachesis** [elsehow/tendermint-tax#6]
Simple fix is to install pandas 1.3.5 which works fine. I also upgraded to requests 2.27.1 and funcy 1.17.

**Comment by elsehow** [comment]
Can you make a PR?

**Comment by elsehow** [comment]
https://github.com/elsehow/tendermint-tax/commit/e5e5a81161132e51b6f1a70845c17bd3a10cd424
