### ISSUE TITLE
Akash address issue

### ISSUE THREAD

**Issue by pmorrow90** [elsehow/tendermint-tax#9]
> (venv) ➜  tendermint-tax git:(main) ✗ python3 tendermint-tax.py --chain akash --address [akashaddress] --ticker AKT --fystart "2021-01-01" --fyend "2021-12-31" --outfile "akash.csv" -v
> 2022-02-28 14:50:02 INFO: Querying RPC for transfer.recipient='[akashaddress]'
> Traceback (most recent call last):
>   File "/Users/zinc-ops/Documents/GitHub/tendermint-tax/venv/lib/python3.9/site-packages/urllib3/connection.py", line 158, in _new_conn
>     conn = connection.create_connection(
>   File "/Users/zinc-ops/Documents/GitHub/tendermint-tax/venv/lib/python3.9/site-packages/urllib3/util/connection.py", line 80, in create_connection
>     raise err
>   File "/Users/zinc-ops/Documents/GitHub/tendermint-tax/venv/lib/python3.9/site-packages/urllib3/util/connection.py", line 70, in create_connection
>     sock.connect(sa)
> ConnectionRefusedError: [Errno 61] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/zinc-ops/Documents/GitHub/tendermint-tax/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 597, in urlopen
>     httplib_response = self._make_request(conn, method, url,
>   File "/Users/zinc-ops/Documents/GitHub/tendermint-tax/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 354, in _make_request
>     conn.request(method, url, **httplib_request_kw)
>   File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1285, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1331, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1280, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1040, in _send_output
>     self.send(msg)
>   File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 980, in send
>     self.connect()
>   File "/Users/zinc-ops/Documents/GitHub/tendermint-tax/venv/lib/python3.9/site-packages/urllib3/connection.py", line 181, in connect
>     conn = self._new_conn()
>   File "/Users/zinc-ops/Documents/GitHub/tendermint-tax/venv/lib/python3.9/site-packages/urllib3/connection.py", line 167, in _new_conn
>     raise NewConnectionError(
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x11bb5e610>: Failed to establish a new connection: [Errno 61] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/zinc-ops/Documents/GitHub/tendermint-tax/venv/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
>     resp = conn.urlopen(
>   File "/Users/zinc-ops/Documents/GitHub/tendermint-tax/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 637, in urlopen
>     retries = retries.increment(method, url, error=e, _pool=self,
>   File "/Users/zinc-ops/Documents/GitHub/tendermint-tax/venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 399, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='135.181.60.250', port=26657): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11bb5e610>: Failed to establish a new connection: [Errno 61] Connection refused'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/zinc-ops/Documents/GitHub/tendermint-tax/tendermint-tax.py", line 60, in <module>
>     txs = util.historical_txs(rpc, query)
>   File "/Users/zinc-ops/Documents/GitHub/tendermint-tax/lib/util.py", line 51, in historical_txs
>     res = tx_search(rpc, query, per_page=str(per_page))
>   File "/Users/zinc-ops/Documents/GitHub/tendermint-tax/lib/util.py", line 43, in tx_search
>     resp = post(rpc, json=q)
>   File "/Users/zinc-ops/Documents/GitHub/tendermint-tax/venv/lib/python3.9/site-packages/requests/api.py", line 117, in post
>     return request('post', url, data=data, json=json, **kwargs)
>   File "/Users/zinc-ops/Documents/GitHub/tendermint-tax/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/Users/zinc-ops/Documents/GitHub/tendermint-tax/venv/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/Users/zinc-ops/Documents/GitHub/tendermint-tax/venv/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
>     r = adapter.send(request, **kwargs)
>   File "/Users/zinc-ops/Documents/GitHub/tendermint-tax/venv/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPConnectionPool(host='135.181.60.250', port=26657): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11bb5e610>: Failed to establish a new connection: [Errno 61] Connection refused'))

**Comment by elsehow** [comment]
Fixed in e5e5a81161132e51b6f1a70845c17bd3a10cd424

Also, please format code with [Markdown code formatting](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks) in the future.
